# AI System Configuration

# Basic configuration for the AI system
ai_system:
  name: "Personal AI Assistant"
  version: "0.1.0"
  environment: "development"
  
  # Feature flags for AB testing
  features:
    smart_responses: false
    context_awareness: false
    learning_mode: false
    advanced_reasoning: false
  
  # AB testing configuration
  ab_testing:
    enabled: true
    default_group: "control"
    test_percentage: 50
    
  # Logging and monitoring
  logging:
    level: "info"
    format: "json"
    
  # Performance settings
  performance:
    max_response_time: 2000  # milliseconds
    max_memory_usage: 512    # MB
    
  # Safety and ethics
  safety:
    content_filter: true
    privacy_protection: true
    bias_detection: true